### ISSUE TITLE
Update nh-launcher to match new config and calling parameters

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/nh-launcher#103]
In <https://github.com/neighbour-hoods/sensemaker-lite/issues/69> we updated the sensmaker. The dashboard needs to be updated to be compatible.

- [ ] Update dependency for sensemaker
- [ ] Update ui/app/src/default_applet_config.ts
- [ ] Anything that is not obvious that might break during testing

**Comment by weswalla** [comment]
@nick-stebbings are you working on this?

**Comment by nick-stebbings** [comment]
> @nick-stebbings are you working on this?

No I am currently doing the global dimension/range/method config screen

**Comment by weswalla** [comment]
ok well since `default_applet_config` is not used any more (we should make a separate ticket for removing any references to it and perhaps an updated model for representing SM primitives that come from applet configs vs global configuration), I think this ticket will be solved by your work with https://github.com/neighbour-hoods/nh-launcher/issues/96, as the only required changes should be updating dependency versions like in https://github.com/neighbour-hoods/todo-applet/pull/23

**Comment by weswalla** [comment]
I created a ticket for removing `default_applet_config` references (https://github.com/neighbour-hoods/nh-launcher/issues/104) and tickets related to updating how we store primitives in the client store (https://github.com/neighbour-hoods/sensemaker-lite/issues/73).

**Comment by adaburrows** [comment]
Closing, since the work @nick-stebbings is doing should include upgrading the sensemaker dependency.
