### ISSUE TITLE
NH Launcher design system

### ISSUE THREAD

**Issue by julioholon** [neighbour-hoods/nh-launcher#35]

**Comment by adaburrows** [comment]
There are multiple moving parts to this:

1. [x] @herramienta-digital, get tokens.json to a stable version.
2. [x] ~~Merge in https://github.com/herramienta-digital/nh-css-styles/tree/develop.~~ (Not necessary with new repo.)
4. [x] Rearrange https://github.com/neighbour-hoods/css-styles to have an `assets` folder for static assets with sub directories for each static asset type.
5. [x] Remove the existing `nh-style-*.css` files since these will now be generated from the `tokens.json` file.
6. [x] Make a [Style Dictionary](https://amzn.github.io/style-dictionary/#/using_the_npm_module) `build.js` or `build.ts` file to use the `tokens.json` file from https://github.com/herramienta-digital/nh-css-styles/blob/develop/tokens/tokens.json and split it into pallet, fonts, typography, and theme files with the `filter` option.
6. [x] Ensure that any references to the fonts are base64 encoded .
8. [x] Use the `css/fonts.css` format to generate the `fonts.css` file.

**Comment by nick-stebbings** [comment]
After our talk the other day in the design session about the design tokens being up to date:
I had another look just to check, and I am sure they are not synced up with the Figma styles!

As an example: 
Looking in https://github.com/herramienta-digital/nh-css-styles/blob/develop/tokens/tokens.json
which is the develop branch and has the most up to date commit -
If i search for #3D3443 which is listed as `theme/bg/surface` in the mock ups, I only find it under `eggplant/600`. If I look for `theme.bg.surface` in the tokens I find `{colors.black}`.

Pablo/Kasimir perhaps you could look into getting these update before DWeb and we could move forward with these tasks. For the moment I am using my own adapter file so that the css variable names will at least be correct in the frontend code.

**Comment by Kasimirsuterwinter** [comment]
The tokens are all up to date in that branch. That is the one we pull from for the Tokens Studio plugin. 

You can find the tokens for the NH Dark Theme here: https://github.com/herramienta-digital/nh-css-styles/blob/211f4dcfa2f36d73448e62eff7348a9190f063f5/tokens/tokens.json#L1570

I think there might be some confusion around how the tokens are defined. The color code #3D3443 is only defined in the based tokens `"base/colors":` and then after that it is referenced by the token `eggplant/600` so in the theme `dark_nh` the `theme.bg.surface` is set to `eggplant/600` 

Something like this. 

```
  "themes/dark_nh": {
     "theme": {
        "bg": {
          "surface": {
            "value": "{colors.eggplant.600}",
            "type": "color"
          },
   },
``` 

Hope this helps to clarify things.

**Comment by nick-stebbings** [comment]
After discussing some of the points on this card in a session with @herramienta-digital  and @Kasimirsuterwinter  we felt that some of these items might no longer be necessary to create a pipeline for these styles:
- Maybe we can repackage my neighbourhoods-design-system-components and use that for the responsibility of injecting styles/adapters, whilst leaving this package just for the building of styles and exposing of assets
- Maybe the easiest way to do that is to run our build script (currently on the `style-tokens` branch of nh-launcher ) with a github action whenever the css repo is commited to. Also another github action to merge from @herramienta-digital automatically.

We will need a sync with other people involved @pospi @adaburrows  to see if we were missing anything with this approach

**Comment by adaburrows** [comment]
Closing since the scope of this ticket has been finished.
