### ISSUE TITLE
Do Applets Need `appWebsocket`?

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/nh-launcher#56]
As I think about #51, I question the need for applets to have access to the `AppWebsocket`.

Can any of you think of a situation where an applet would need to make zome calls to other cells in the conductor directly through the `AppWebsocket`?

If not, I think passing through the `AppAgentWebsocket` is enough (and more secure because it constrains zome calls only to the applet happ).

Regarding cross applet calls/rendering/etc, I figure this could be mediated through the sensemaker store, which every applet will have access to.

Thoughts? @nick-stebbings @pospi @adaburrows @julioholon

**Comment by julioholon** [comment]
Makes sense to keep only **AppAgentWebsocket**, unless we have a good reason to give full access. Would this bring any other benefit other than simplicity and more security?

**Comment by weswalla** [comment]
@julioholon nope, those are the main 2 benefits I see.

**Comment by pospi** [comment]
> Can any of you think of a situation where an applet would need to make zome calls to other cells in the conductor directly through the AppWebsocket?

\*raises hand awkwardly\*

hREA Applets are composed of multiple cells, so really in this parameter model one would require multiple `AppAgentWebsocket`s as parameters in order to cleanly write some initialisation bindings.

At present I'm working around this by [referring to the internals of `AppWebsocket`](https://github.com/neighbour-hoods/timetracking-applet/blob/935fc449aac6f6737f074dedc677e3d8e7a62c33/ui/src/provider-app-test-harness.ts#L95) to get at the conductor URI. So long as we remain compatible with some way of doing the same through an `AppAgentWebsocket` and we can still [enumerate `appInfo.cell_info`](https://github.com/h-REA/hREA/blob/8df5b010d85409f06674cc508ef26913fde8d00f/modules/vf-graphql-holochain/connection.ts#L126C18-L126C35) based on the Applet's hApp ID, hREA's more complex Cell arrangement can boot itself.

:thinking: how do the `appInfo\.(installed_)?app_id` & `cellInfo.role_name` fields from Holochain hApps correspond to Neighbourhoods Applets / Features? Is this potentially an issue..?

**Comment by weswalla** [comment]
I think as long as all the dnas in an applet are bundled as one happ, then an `AppAgentWebsocket` should provide access to all cells in the happ. Is there anything different about the way hrea dnas are composed into a happ bundle?

**Comment by pospi** [comment]
No, that should be fine then :+1:

**Comment by adaburrows** [comment]
POLA: Principle of Least Access. Things should only be given access to what they absolutely need to run. Anything more is asking for trouble.

**Comment by adaburrows** [comment]
@weswalla Is this something that we have already acted on?

**Comment by adaburrows** [comment]
Only appAgentWebsocket is passed in.
