### ISSUE TITLE
[REFACTOR] add routing to app?

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/nh-launcher#65]
There is currently no routing in the app and most of the navigation logic exists as conditional rendering in the `main-dashboard` component, based on these properties:
```typescript
  /**
   * Defines the content of the dashboard
   */
  @state()
  private _dashboardMode: DashboardMode = DashboardMode.MainHome;

  /**
   * Defines the content of the navigation panels (left sidebar (primary) and top bar (secondary))
   */
  @state()
  private _navigationMode: NavigationMode = NavigationMode.Agnostic;
  ```
  With the following type definitions:
  ```typescript
  export enum DashboardMode {
  MainHome,
  WeGroupHome,
  AssessmentsHome,
  AppletGroupInstanceRendering,
  AppletClassHome,
  AppletClassRendering,
  Loading,
}

export enum NavigationMode {
  AppletCentric,
  GroupCentric,
  Agnostic,
}
```

The downside to this approach is that upon page refresh the whole navigate state is wiped and the user is brought back to the home page.

Routing would help us encapsulate initialization logic depending on the navigation context and decompose the monolithic dashboard component into smaller and more manageable components.

The routes could be something like:
`/` - main page
`/:neighbourhoodId/` - home page of a neighbourhood
`/:neighbourhoodId/dashboard` - dashboard view of a neighbourhood
`/:neighbourhoodId/:appletId` - main view of an applet within a neighbourhood

Routing libs we can use: 
- [@vaadin/router - npm](https://www.npmjs.com/package/@vaadin/router)
- [@lit-labs/router - npm](https://www.npmjs.com/package/@lit-labs/router)

**Comment by weswalla** [comment]
thoughts @nick-stebbings @pospi @adaburrows ?

**Comment by nick-stebbings** [comment]
@weswalla This is definitely going to be useful and a simple way to maintain a bit of state.
Is there a routing library for Lit we can use already?

**Comment by pospi** [comment]
I have had a lot of breakages and issues with routing libs inside the Tauri runtime. I think the Holochain Launcher does [some stuff](https://github.com/neighbour-hoods/marketplace-applet/issues/1#issuecomment-1649153367) that interferes ([see "open_url_cmd"](https://github.com/holochain/launcher/blob/52481d5ce78283d588af6dc52555a5bdded073a7/crates/holochain_launcher_utils/src/shared_commands.rs#L4)).

In another project we are running our [development UI through `hc launch`](https://github.com/Carbon-Farm-Network/app-carbon-farm-network/blob/894e97d641d7fe202c6df283e975bcba5f793339/package.json#L14). SvelteKit's built-in routing seems to work fine there but alas when I dig deeper it [seems this is done](https://github.com/sveltejs/kit/blob/a58f0491ecbd91cc3729836b6940066b1ee7317c/packages/kit/src/exports/index.js) at an HTTP server level during development (which is not a process overhead we want to incur within a standard NH Launcher runtime environment).

But I'm confident (confirming with a usergroup) that it's also been working when built as an SPA and run via the Holochain Launcher. Whatever magic the `@sveltejs/kit/vite` plugin does for `import { goto } from '$app/navigation'` is where a workable solution can be found.

We *could* even just setup the NH Launcher and other Applet repos as Sveltekit / Vite repos. Doesn't mean we have to use Svelte's ecosystem for anything other than routing- Lit works just fine in that context and you can setup any UI element as a `.ts` file same as a `.svelte` file.  
But it would also give us an avenue to explore RE moving to a Svelte-based component implementation 'cos honestly I think we could reduce verbosity quite a bit for most components.  
Or we could figure out whatever is being injected for `$app/navigation` at runtime and load that (or something that relies on the same mechanism) into our existing LitElement toolchain directly. Either works.

@weswalla is the `hc launch` and local UI development server method what we intend on using for NH Applet development moving forward?

**Comment by adaburrows** [comment]
I just realized I had talked about this in meetings with people but never put forth a definitive take on these sorts of things, so here goes:

## There are three issues here:
1. We want state management that extends through what page is shown.
2. Applet devs likely want an easy way of porting apps with routing into our ecosystem.
3. The interaction between the two above potentially contradictory aims.

### The problem with routing in the holochain-launcher-utils

There's a few interesting things that happen with the Tauri code and event handlers that the Holochain team have written:
1. There's a custom [`open_url_cmd` Tauri command](https://github.com/holochain/launcher/blob/0522c05e485e00987d6a086de520802b714bf1c7/crates/holochain_launcher_utils/src/shared_commands.rs#L4) that handles opening urls that is pretty simple and naive. It just makes sure that the url is prefixed with `http://` or `https://`. If it is it uses the [`open` crate to load the data](https://crates.io/crates/open), and this might actually cause a bug with URLs that are from `tauri.localhost`, but I'd need to step through the code.
2. The custom Rust code written for setting up new windows injects an event handler that intercepts every single link and sends it through the `open_url_cmd`. There are actually two versions of the code, one for [MacOS](https://github.com/holochain/launcher/blob/0522c05e485e00987d6a086de520802b714bf1c7/crates/holochain_launcher_utils/src/window_builder.rs#L48) and one for [other OSes](https://github.com/holochain/launcher/blob/0522c05e485e00987d6a086de520802b714bf1c7/crates/holochain_launcher_utils/src/window_builder.rs#L66). This is interesting because instead of just letting what would likely happen when following a link that initiates a [`pushState()`](https://developer.mozilla.org/en-US/docs/Web/API/History_API/Working_with_the_History_API) call (what most client side routing would likely be doing), it instead tries to load the URL which fails since there is not server to serve that URL or file that corresponds to that URL. This means that this event handler is interrupting the normal flow of events that initiates the `pushState()` --or-- there is likely some code deep inside Tauri or wry that is firing the code to open a URL when it shouldn't.

### State management

Given the above issues, we should probably just rely on really good state management. There are a few things that could probably help this transition:

- Every URL that corresponds to a route represents a page.
- Each page represents a particular high level application state.
- Each page may have multiple states it might actually be in.
- The combination of these two bits of state are typically not managed properly by routing anyways, so implementing a better solution that manages state explicitly would likely help us minimize bugs.

### Applet devs need "routing" that is easy to port their app over to

Why port their app?

- Because of the issues above that would need to be fixed with the event hook added by the Rust code in Tauri interfering with push state.
- Because we are not putting apps in their own iframe so their routing would overwrite our routing and there is no consistent way to give them a way to append their url to our app url somewhere. It would require writing code that hooks into each and every possible routing system that any app could use and attempting to monkey patch it.

So that means we need to a really quick and easy system to possible replace both their navigation and routing system with something that would be compatible with our top level state management so they aren't overwriting our URLs/state and navigating away with our top level navigation becomes easy.

### Why are the two above objectives possibly at odds?

Well, I think the second point mentioned above is the main reason. Without any clear way to ensure two routing systems don't interfere with each other there is no point in enabling any app to use routing. The hurdles are the same as above, to use routing, we'd need to separate apps out into their own URL space by giving them an iframe in which to run. Then we'd need to solve the issue causing us to have issues with `pushState()` routing in Launcher/Tauri/wry.

Of course, we can do a few experiments to understand what is going on. We could try to run an app that uses `pushState()` routing in plain Tauri without Holochain or the launcher. If that works, then we can reasonably say that the hook being added in to all anchor links is the culprit. But we'd still need to put each app in an iframe.

**Comment by adaburrows** [comment]
Given some of the new stories that we're creating in our product discussions, a lot of this stuff will get ironed out in a few stories that will be added soon.

However, I will summarized some of the thoughts that I've thought through:
* If we use the holochain launcher code, routing will be broken since it expects to be able to load the URLs each time something is clicked, but those URLs don't exist anywhere except in the front end routing. So this means we should just use better state management.
* If we use want people to be able to easily migrate their existing web apps by upgrading them slowly to work with Neighbourhoods, the holochain launcher code will reload the app from the server each time. So we'll want to migrate away from the holochain launcher.
* Applications will not want to change out their existing routing code. Anything that requires developers to overhaul their apps in that manner is a huge impedance. So anything we come up with will need to provide an interface that uses postMessage in an iFrame and other loading mechanisms for components that are meant to run in our context.

So, we're left with running in iFrames, keeping existing app routing and frameworks in place, postMessage, manifests, and other normal web tech for composing these things together. We're also left with a lot of work to spec out how it does all fit together, but that's expected.
