### ISSUE TITLE
Redesign Applet renderer interface

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/nh-launcher#73]
Currently the applets [define a `full` callback function](https://github.com/neighbour-hoods/todo-applet/blob/82b2a044c672c0ccea7d7c7dfed633081394ca50/ui/src/applet-index.ts#L37) which is responsible for the internals of:

- registering the relevant CustomElement
- rendering it, and
- passing the appropriate Sensemaker attributes to the component

This creates a tight coupling between Applet code and the Launcher which is quite brittle. The functionality appears to be generic to all Applets.

This logic should be genericised and (probably) made the responsibility of `RenderBlock`. Applet module interfaces need to be redefined accordingly to export something more simple- probably just the CustomElement classes themselves.

See https://custom-elements-manifest.open-wc.org/analyzer/getting-started/ for possible overlap with the CustomElements Manifest spec.

This decision will impact the final implementation for https://github.com/neighbour-hoods/design-system-components/issues/13.

**Comment by adaburrows** [comment]
Thanks! This is a good summary. I do favor exposing the custom elements from the applet directly. There's just some additional metadata we need to think through to make sure we know what types the resource view components can be used with (and which resource def entry hash they should be associated with during installation).

**Comment by pospi** [comment]
I know it's a stretch but I want to float also that I really like the idea of Applet devs being able to simply author CustomElements with well-defined attribute names, and that the Launcher can be smart enough to pick those up and know what's what.

eg. if my CustomElement has a attributes of name "resourceEh" and "dimensionEh" then we know that it is an Assessment display widget.

Or failing that we can probably explore neat convenience features like class decorators which hook in to the CustomElements Manifest Analyzer somehow, to inject additional Neighbourhoods-specific properties that the Launcher can pick up on.

**Comment by adaburrows** [comment]
> I know it's a stretch but I want to float also that I really like the idea of Applet devs being able to simply author CustomElements with well-defined attribute names, and that the Launcher can be smart enough to pick those up and know what's what.

That really close to one of the ideas I floated a while ago, though I was thinking we could potentially package them separately as just a package with a Web Component and a manifest that defines the data we need. I was also thinking that this could be stored in a separate "components" zome akin to the Matrix zome we have now.

The big issue with some of this will be refactoring the matrix zome and nh-launcher to work with the separation of components from the app (though really, the app is just a different component bundled with a hApp). Then we need to refactor what we just wrote since that would change how components are also loaded and used from an app and the old WeApplet interface.

**Comment by weswalla** [comment]
One thing we will want to keep in mind is allowing applet developers to set up their applet context specific to the FE framework they choose, especially when using widget components imported from a library, like `SensemakeResource`: https://github.com/neighbour-hoods/sensemaker-lite/blob/48ed9174c20b5fe1955dfeae0771e8ed9bd90d98/client/src/widgets/sensemake-resource.ts#L13-L15 which expects Lit specific context to be provided.

**Comment by pospi** [comment]
Well actually I think that Lit context lib might be a polyfill for some proposed browser feature? So it might be more a case of identifying which context libraries from other frameworks are standards-compatible.
Either that and/or we provide our own context binding components which pass the located context through as props to their slotted child element, which would allow third-party app developers to integrate with a properties interface alone.

> The big issue with some of this will be refactoring the matrix zome and nh-launcher to work with the separation of components from the app

If we are going to rewrite large swathes of `MatrixStore` for #43 then this might be the time to start refactoring out. We can develop elements of the new & current functionality with more narrow scope; and remove chunks of `MatrixStore` to be replaced with calls to these new zomes & APIs as we go. Ideally each functional unit can be separable all the way down to the data storage Cell. And we wrap areas of `MatrixStore` in tests as we go, so that we can ensure the replacement functionality works as intended when swapped in.

**Comment by adaburrows** [comment]
The [@lit-labs/context](https://github.com/lit/lit/tree/main/packages/labs/context) which is really just an implementation in Lit of the [Web Components Community Protocol Proposal for the Context Protocol](https://github.com/webcomponents-cg/community-protocols/blob/main/proposals/context.md). There's nothing special about it and anything that implements itself as a WebComponent can use a context provider or become a context provider.

What is different is how some other front end lib, like React, define a "context" where the data passing is similarly handled by even dispatching, but it uses the internal hook architecture to ensure the rendering changes are dispatched properly (the technical details are fairly complicated). However, one could always create an adapter for React using the same trickery I use in my data store: https://github.com/lightningrodlabs/rea-playspace/blob/main/modules/yaati/src/ReactHook.ts

**Comment by adaburrows** [comment]
I should say the spec does specifically say that contexts are not actually for dependency injection. We should stay away from passing anything through contexts that isn't configuration or state. If we have a context that is being used to inject a SensemakerStore, that is probably a bad design. It should instead be passing in the configuration that is used to initialize the SensemakerStore.

Additionally, the way things are going with the interface, eventually apps may not even need to have direct access to the SensemakerStore. They would rather just be dynamically composed views of resources with slots for certain things to be added which then get their configuration to write to their underlying SensemakerStore config context and their own resource specific stores.

Although, we should think through the ramifications of using this kind of thing with a React based applet (since it's the least WebComponent friendly framework out there). From what I remember, React has issues dealing with WebComponent events without first getting a ref that can be used to set up an event listener. I actually don't think that will impact much, since changes to the store should be what are used to update what is shown on the screen and not using events directly. So I think using Lit contexts between WebComponents with a layer of React rendering between them should be fine, as long as the React code only reacts to a change in the underlying store using the `useSyncExternalStore`/`useSyncExternalStoreWithSelector` hook. There may be a necessity to defer the updates to the store until after the current rendering cycle, but that's just good form.

**Comment by adaburrows** [comment]
Also, as a counterpoint to the thought of:
> This creates a tight coupling between Applet code and the Launcher which is quite brittle.

There is necessarily a tight coupling. It's not like someone can write a WordPress plugin and use it in Drupal (still in PHP, but would need a complete adaptor for the WrodPress API) or Lemmy (written in Rust with a completely different architecture).

Anything that is going to be made into a app should do some internal refactoring to allow configuring/injecting different dependencies into the main component of the application.

That means that any component exposed by a nh-launcher / sensemaker enabled applet will necessarily need to conform to an API that we create to give it the configuration, Holochain clients, or stores to be able to interact with the things with which it needs to interact. It will always have to get those thing from us in a specific manner, just like it would need to get them from it's own self hosted version, Holochain launcher version, or some other framework based version in a distinct yet tightly coupled manner to the API being used. It's just like writing a plugin for any other platform with it's own unique API.

So I'm not opposed to having a component need to have a very specific interface to be passed what it needs to use. I'd rather have it be done by props than by contexts, especially if it's not just configuration, but also dependency injection.
