### ISSUE TITLE
Configure embedded Tauri build

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/nh-launcher#81]
We need to do this in order to implement privileged methods which have access to the filesystem. It may also be necessary for adding custom routing logic (see #65).

Required for #43 to be implemented.

**Comment by pospi** [comment]
Not committing icons for now to avoid bloating the repo. @Kasimirsuterwinter do we have a 512x512 of a suitable Neighbourhoods logo someplace?

Files list to add to `src-tauri/icons`:

```
32x32.png
128x128.png
128x128@2x.png
icon.icns
icon.ico
icon.png (512x512)
Square30x30Logo.png
Square44x44Logo.png
Square71x71Logo.png
Square89x89Logo.png
Square107x107Logo.png
Square142x142Logo.png
Square150x150Logo.png
Square284x284Logo.png
Square310x310Logo.png
StoreLogo.png (50x50)
```

(Probably should also look at the docs and see if *all* these formats are really needed...)

**Comment by pospi** [comment]
See also https://github.com/holochain/launcher/blob/develop/default.nix

**Comment by adaburrows** [comment]
Considering how even the LRL team has moved away from Tauri, things don't look good for anything written using it in Holochain land. However, that may still be from the issues that has been introduced with the URL handlers. But I do remember some drastically incorrect CSS rendering when using the `hc launch` command. So it's possible we just have to move away to Electron. Also, it's possible we need to just move to making sure everything can run in a browser using our own version of holo, since holo also doesn't let apps install other apps. Plus electron doesn't support mobile and if we need to create a new version of the styling for mobile for it to be usable in Tauri, then it's also not worth it.
